---
skylounge-config:
  id: "skylounge.yml"
  uri: "sky-lounge/hello-gradlew/skylounge.yml"
  oid: "b754fba11d8c051d48645657a3e023e281ff8a27"
  version-url: "/sky-lounge/hello-gradlew/blob/b754fba11d8c051d48645657a3e023e281ff8a27/skylounge.yml"
blueprint:
  id: "blueprint"
  uri: "sky-lounge/skylounge-library/blueprints/gcp/cloud-run/blueprint.yml"
  oid: "c3b2cb916788b41483e81c95be93ca963a46b89b"
  version-url: "/sky-lounge/skylounge-library/blob/c3b2cb916788b41483e81c95be93ca963a46b89b/blueprints/gcp/cloud-run/blueprint.yml"
workflows:
- id: "development"
  uri: "sky-lounge/skylounge-library/blueprints/gcp/cloud-run/workflow-templates/development.yml"
  oid: "13767aaac5d24ecd055b6e2c19580c2bfe120f81"
  version-url: "/sky-lounge/skylounge-library/blob/13767aaac5d24ecd055b6e2c19580c2bfe120f81/blueprints/gcp/cloud-run/workflow-templates/development.yml"
  jobs:
  - id: "integration-test"
    uri: "sky-lounge/hello-gradlew/skylounge/integration-test.yml"
    oid: "50135f52c23cdbe5f0271b548ad04f5035cc8677"
    version-url: "/sky-lounge/hello-gradlew/blob/50135f52c23cdbe5f0271b548ad04f5035cc8677/skylounge/integration-test.yml"
  steps:
  - id: "build-container-image"
    uri: "sky-lounge/skylounge-library/steps/pack/gradlew/build.yml"
    oid: "43cb5d9a7f495643816445771a2209e658f30e37"
    version-url: "/sky-lounge/skylounge-library/blob/43cb5d9a7f495643816445771a2209e658f30e37/steps/pack/gradlew/build.yml"
- id: "promote"
  uri: "sky-lounge/skylounge-library/blueprints/gcp/cloud-run/workflow-templates/promote.yml"
  oid: "053d3316ef70eeb15f770d1a41ff851f8bbb5eec"
  version-url: "/sky-lounge/skylounge-library/blob/053d3316ef70eeb15f770d1a41ff851f8bbb5eec/blueprints/gcp/cloud-run/workflow-templates/promote.yml"
  jobs: []
  steps: []
- id: "production"
  uri: "sky-lounge/skylounge-library/blueprints/gcp/cloud-run/workflow-templates/production.yml"
  oid: "0db4fc37df11b3863a51f8842a55a67307dc7f62"
  version-url: "/sky-lounge/skylounge-library/blob/0db4fc37df11b3863a51f8842a55a67307dc7f62/blueprints/gcp/cloud-run/workflow-templates/production.yml"
  jobs: []
  steps: []
- id: "daily-scans"
  uri: "sky-lounge/skylounge-library/blueprints/gcp/cloud-run/workflow-templates/daily-scans.yml"
  oid: "bd423aab0d0aa3190bf9808906c8699aa3b23299"
  version-url: "/sky-lounge/skylounge-library/blob/bd423aab0d0aa3190bf9808906c8699aa3b23299/blueprints/gcp/cloud-run/workflow-templates/daily-scans.yml"
  jobs: []
  steps: []
